apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-08-23T04:54:17Z"
  generation: 1
  labels:
    app: test
  name: test
  namespace: default
  resourceVersion: "3347200"
  uid: 087fc65c-e374-4afa-a529-c57178adc0c1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: mmeetengineer/mynodejs:0.0.1.RELEASE
        imagePullPolicy: IfNotPresent
        name: mynodejs
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}

